spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.103:9092
          zkNodes: 192.168.0.103
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json
