spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.103:9092
          zkNodes: 192.168.0.103
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json

  datasource:
    url: jdbc:postgresql://localhost:5432/ms
    username: postgres
    password: 123456

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update

server:
  port: 8081


